CREATE TABLE RAG_DOCUMENTO (
    ID_DOCUMENTO       INT NOT NULL AUTO_INCREMENT,
    TITULO             VARCHAR(255) NOT NULL,
    FICHERO            VARCHAR(128) NOT NULL,
    IDIOMA             VARCHAR(2)   NOT NULL,
    FECHA_DOCUMENTO    DATE,
    USUARIO            VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_DOCUMENTO)
) ENGINE=InnoDB;
GRANT INSERT, UPDATE, SELECT, DELETE on RAG_DOCUMENTO TO rag;

CREATE TABLE RAG_DOCUMENTO_CHUNK (
    ID_CHUNK       INT NOT NULL AUTO_INCREMENT,
    ID_DOCUMENTO   INT NOT NULL,
    CONTENT_CHUNK  LONGTEXT NOT NULL,
    EMBEDDING      VECTOR(768) NOT NULL,
    PRIMARY KEY (ID_CHUNK),
    VECTOR INDEX (EMBEDDING) DISTANCE=cosine,
    CONSTRAINT FK_CHUNK_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES RAG_DOCUMENTO(ID_DOCUMENTO) ON DELETE CASCADE
) ENGINE=InnoDB;

GRANT INSERT, UPDATE, SELECT, DELETE on RAG_DOCUMENTO_CHUNK to rag;

CREATE TABLE RAG_CONFIGURACION (
   ID_CONFIG   INT NOT NULL AUTO_INCREMENT,
   CLAVE       VARCHAR(256) NOT NULL,
   VALOR       VARCHAR(1024) NOT NULL,
   ENTORNO     VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_CONFIG)
) ENGINE=InnoDB;
GRANT INSERT, UPDATE, SELECT, DELETE on RAG_CONFIGURACION TO rag;
